spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaoyuan_diancan
    username: root
    password: Lcq123!

mybatis-plus:
  mapper-locations: mapper/*.xml
  global-config:
    db-config:
      # 主键策略
      id-type: auto
      # 表名前缀
      # table-prefix: t
      # 表名是否使用下划线间隔，默认：是
      table-underline: true
  # 添加mybatis配置文件路径
  # config-location: mybatis-config.xml
  # 配置实体类包地址
  type-aliases-package: com.luochaoqun.plus.ideas.xiaoyuandiancan.*.entity
  # 驼峰转下划线
  configuration:
    map-underscore-to-camel-case: true

file:
  upload:
    url: /Users/luochaoqun/Documents/file-server
    imgMaxSize: 10240